title: "Contestability Workshop at CSCW 2019"
description: ""

search: false

author:
  name     : "Kristen Vaccaro"
  avatar   : "/"
  bio      : " "
  location : "Austin, TX" 

footer:

plugins:
  - jekyll-include-cache

remote_theme: mmistakes/minimal-mistakes

# Defaults
